[2024-10-29T17:30:29.119+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-29T17:30:29.152+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: join_and_feature_engineer_all_data.join_and_merge manual__2024-10-29T14:30:15.385142+00:00 [queued]>
[2024-10-29T17:30:29.159+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: join_and_feature_engineer_all_data.join_and_merge manual__2024-10-29T14:30:15.385142+00:00 [queued]>
[2024-10-29T17:30:29.160+0000] {taskinstance.py:2306} INFO - Starting attempt 5 of 5
[2024-10-29T17:30:29.170+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): join_and_merge> on 2024-10-29 14:30:15.385142+00:00
[2024-10-29T17:30:29.181+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1656) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-29T17:30:29.184+0000] {standard_task_runner.py:63} INFO - Started process 1661 to run task
[2024-10-29T17:30:29.183+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'join_and_feature_engineer_all_data', 'join_and_merge', 'manual__2024-10-29T14:30:15.385142+00:00', '--job-id', '223', '--raw', '--subdir', 'DAGS_FOLDER/stock_data_pipelines.py', '--cfg-path', '/tmp/tmpx71hxsh0']
[2024-10-29T17:30:29.186+0000] {standard_task_runner.py:91} INFO - Job 223: Subtask join_and_merge
[2024-10-29T17:30:29.210+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-29T17:30:29.261+0000] {task_command.py:426} INFO - Running <TaskInstance: join_and_feature_engineer_all_data.join_and_merge manual__2024-10-29T14:30:15.385142+00:00 [running]> on host a5e3407ec3e4
[2024-10-29T17:30:29.357+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='join_and_feature_engineer_all_data' AIRFLOW_CTX_TASK_ID='join_and_merge' AIRFLOW_CTX_EXECUTION_DATE='2024-10-29T14:30:15.385142+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-29T14:30:15.385142+00:00'
[2024-10-29T17:30:29.358+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-29T17:30:29.568+0000] {logging_mixin.py:188} INFO -       transaction_date ticker           executive  ...    shares share_price symbol
32639       2003-08-14   AMZN  WILSON, L MICHELLE  ...   37502.0     39.8960   AMZN
32638       2003-08-14   AMZN  WILSON, L MICHELLE  ...   37502.0      0.0000   AMZN
32637       2003-08-14   AMZN  WILSON, L MICHELLE  ...   37502.0      7.9300   AMZN
32636       2003-08-15   AMZN    BEZOS, JEFFREY P  ...    1300.0      0.0000   AMZN
32635       2003-08-15   AMZN    BEZOS, JEFFREY P  ...  100000.0     40.1648   AMZN
32634       2003-08-18   AMZN  DALZELL, RICHARD L  ...  137500.0      8.5500   AMZN
32633       2003-08-18   AMZN  DALZELL, RICHARD L  ...  137500.0      0.0000   AMZN
32632       2003-08-18   AMZN    BEZOS, JEFFREY P  ...  100000.0     41.7664   AMZN
32631       2003-08-19   AMZN    BEZOS, JEFFREY P  ...  100000.0     43.4566   AMZN
32630       2003-08-19   AMZN   GORDON, WILLIAM B  ...   20000.0     43.0500   AMZN

[10 rows x 9 columns]
[2024-10-29T17:30:29.583+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-29T17:30:29.584+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/feature_engineer_and_join_data.py", line 23, in join_and_merge_datasets
    final_df = pd.merge(merged_df, technical_indicators_data, on=['ticker', 'date'], how='left')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/merge.py", line 169, in merge
    op = _MergeOperation(
         ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/merge.py", line 791, in __init__
    ) = self._get_merge_keys()
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/merge.py", line 1269, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 1844, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'ticker'
[2024-10-29T17:30:29.618+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=join_and_feature_engineer_all_data, task_id=join_and_merge, run_id=manual__2024-10-29T14:30:15.385142+00:00, execution_date=20241029T143015, start_date=20241029T173029, end_date=20241029T173029
[2024-10-29T17:30:29.629+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 223 for task join_and_merge ('ticker'; 1661)
[2024-10-29T17:30:29.683+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-29T17:30:29.704+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-29T17:30:29.706+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
