[2024-10-29T20:26:41.415+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-29T20:26:41.443+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: feature_engineer_news_sentiment_data.engineer_sentiment_features manual__2024-10-29T20:26:36.369839+00:00 [queued]>
[2024-10-29T20:26:41.449+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: feature_engineer_news_sentiment_data.engineer_sentiment_features manual__2024-10-29T20:26:36.369839+00:00 [queued]>
[2024-10-29T20:26:41.450+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-29T20:26:41.459+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): engineer_sentiment_features> on 2024-10-29 20:26:36.369839+00:00
[2024-10-29T20:26:41.471+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1406) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-29T20:26:41.473+0000] {standard_task_runner.py:63} INFO - Started process 1411 to run task
[2024-10-29T20:26:41.471+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'feature_engineer_news_sentiment_data', 'engineer_sentiment_features', 'manual__2024-10-29T20:26:36.369839+00:00', '--job-id', '249', '--raw', '--subdir', 'DAGS_FOLDER/stock_data_pipelines.py', '--cfg-path', '/tmp/tmpub3g3m27']
[2024-10-29T20:26:41.474+0000] {standard_task_runner.py:91} INFO - Job 249: Subtask engineer_sentiment_features
[2024-10-29T20:26:41.494+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-29T20:26:41.537+0000] {task_command.py:426} INFO - Running <TaskInstance: feature_engineer_news_sentiment_data.engineer_sentiment_features manual__2024-10-29T20:26:36.369839+00:00 [running]> on host cf1c99cdc1a8
[2024-10-29T20:26:41.624+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='feature_engineer_news_sentiment_data' AIRFLOW_CTX_TASK_ID='engineer_sentiment_features' AIRFLOW_CTX_EXECUTION_DATE='2024-10-29T20:26:36.369839+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-29T20:26:36.369839+00:00'
[2024-10-29T20:26:41.626+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-29T20:26:41.690+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-29T20:26:41.691+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/nltk/data.py", line 579, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93mstopwords[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('stopwords')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/stopwords.zip/stopwords/[0m

  Searched in:
    - '/home/***/nltk_data'
    - '/home/***/.local/nltk_data'
    - '/home/***/.local/share/nltk_data'
    - '/home/***/.local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/news_sentiment_data_elt.py", line 51, in extract_features_from_news_data
    news_data = extract_features(news_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/news_sentiment_data_elt.py", line 24, in extract_features
    df['cleaned_summary'] = df['combined_text'].apply(preprocess_text)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/series.py", line 4764, in apply
    ).apply()
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 1209, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 1289, in apply_standard
    mapped = obj._map_values(
             ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/base.py", line 921, in _map_values
    return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/algorithms.py", line 1814, in map_array
    return lib.map_infer(values, mapper, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib.pyx", line 2926, in pandas._libs.lib.map_infer
  File "/opt/airflow/dags/utils/news_sentiment_data_elt.py", line 10, in preprocess_text
    text = ' '.join([word for word in text.split() if word not in stopwords.words('english')])
                                                                  ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/nltk/corpus/util.py", line 120, in __getattr__
    self.__load()
  File "/home/airflow/.local/lib/python3.12/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/nltk/data.py", line 579, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93mstopwords[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('stopwords')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/stopwords[0m

  Searched in:
    - '/home/***/nltk_data'
    - '/home/***/.local/nltk_data'
    - '/home/***/.local/share/nltk_data'
    - '/home/***/.local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

[2024-10-29T20:26:41.716+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=feature_engineer_news_sentiment_data, task_id=engineer_sentiment_features, run_id=manual__2024-10-29T20:26:36.369839+00:00, execution_date=20241029T202636, start_date=20241029T202641, end_date=20241029T202641
[2024-10-29T20:26:41.726+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 249 for task engineer_sentiment_features (
**********************************************************************
  Resource [93mstopwords[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('stopwords')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/stopwords[0m

  Searched in:
    - '/home/***/nltk_data'
    - '/home/***/.local/nltk_data'
    - '/home/***/.local/share/nltk_data'
    - '/home/***/.local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
; 1411)
[2024-10-29T20:26:41.769+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-29T20:26:41.792+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-29T20:26:41.796+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
