[2024-10-29T17:40:49.844+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-29T17:40:49.875+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: join_and_feature_engineer_all_data.engineer_ml_features manual__2024-10-29T14:30:15.385142+00:00 [queued]>
[2024-10-29T17:40:49.881+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: join_and_feature_engineer_all_data.engineer_ml_features manual__2024-10-29T14:30:15.385142+00:00 [queued]>
[2024-10-29T17:40:49.882+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-29T17:40:49.891+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): engineer_ml_features> on 2024-10-29 14:30:15.385142+00:00
[2024-10-29T17:40:49.900+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2407) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-29T17:40:49.902+0000] {standard_task_runner.py:63} INFO - Started process 2412 to run task
[2024-10-29T17:40:49.902+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'join_and_feature_engineer_all_data', 'engineer_ml_features', 'manual__2024-10-29T14:30:15.385142+00:00', '--job-id', '227', '--raw', '--subdir', 'DAGS_FOLDER/stock_data_pipelines.py', '--cfg-path', '/tmp/tmparft869o']
[2024-10-29T17:40:49.905+0000] {standard_task_runner.py:91} INFO - Job 227: Subtask engineer_ml_features
[2024-10-29T17:40:49.924+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-29T17:40:49.966+0000] {task_command.py:426} INFO - Running <TaskInstance: join_and_feature_engineer_all_data.engineer_ml_features manual__2024-10-29T14:30:15.385142+00:00 [running]> on host a5e3407ec3e4
[2024-10-29T17:40:50.054+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='join_and_feature_engineer_all_data' AIRFLOW_CTX_TASK_ID='engineer_ml_features' AIRFLOW_CTX_EXECUTION_DATE='2024-10-29T14:30:15.385142+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-29T14:30:15.385142+00:00'
[2024-10-29T17:40:50.055+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-29T17:40:50.080+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-29T17:40:50.081+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/feature_engineer_and_join_data.py", line 37, in engineer_features
    joined_data['year'] = joined_data['date'].dt.year
                          ~~~~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-10-29T17:40:50.097+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=join_and_feature_engineer_all_data, task_id=engineer_ml_features, run_id=manual__2024-10-29T14:30:15.385142+00:00, execution_date=20241029T143015, start_date=20241029T174049, end_date=20241029T174050
[2024-10-29T17:40:50.106+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 227 for task engineer_ml_features ('NoneType' object is not subscriptable; 2412)
[2024-10-29T17:40:50.157+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-29T17:40:50.179+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-29T17:40:50.180+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
