[2024-10-28T16:12:50.190+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-28T16:12:50.221+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_clean_insider_transaction_data.fetch_insider_transaction_data manual__2024-10-28T15:53:59.592313+00:00 [queued]>
[2024-10-28T16:12:50.228+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_clean_insider_transaction_data.fetch_insider_transaction_data manual__2024-10-28T15:53:59.592313+00:00 [queued]>
[2024-10-28T16:12:50.229+0000] {taskinstance.py:2306} INFO - Starting attempt 8 of 8
[2024-10-28T16:12:50.237+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_insider_transaction_data> on 2024-10-28 15:53:59.592313+00:00
[2024-10-28T16:12:50.245+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1742) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-28T16:12:50.247+0000] {standard_task_runner.py:63} INFO - Started process 1744 to run task
[2024-10-28T16:12:50.247+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_clean_insider_transaction_data', 'fetch_insider_transaction_data', 'manual__2024-10-28T15:53:59.592313+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/stock_data_pipelines.py', '--cfg-path', '/tmp/tmpu6_py8cl']
[2024-10-28T16:12:50.251+0000] {standard_task_runner.py:91} INFO - Job 51: Subtask fetch_insider_transaction_data
[2024-10-28T16:12:50.270+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-28T16:12:50.316+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_and_clean_insider_transaction_data.fetch_insider_transaction_data manual__2024-10-28T15:53:59.592313+00:00 [running]> on host 66a068bd0545
[2024-10-28T16:12:50.409+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_clean_insider_transaction_data' AIRFLOW_CTX_TASK_ID='fetch_insider_transaction_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-28T15:53:59.592313+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-28T15:53:59.592313+00:00'
[2024-10-28T16:12:50.411+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-28T16:12:51.119+0000] {logging_mixin.py:188} INFO - {'Information': 'Thank you for using Alpha Vantage! Our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits.'}
[2024-10-28T16:12:51.122+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-28T16:12:51.124+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/stock_data_elt.py", line 70, in fetch_insider_transaction_data
    df = pd.DataFrame(data['data'])
                      ~~~~^^^^^^^^
KeyError: 'data'
[2024-10-28T16:12:51.159+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=fetch_and_clean_insider_transaction_data, task_id=fetch_insider_transaction_data, run_id=manual__2024-10-28T15:53:59.592313+00:00, execution_date=20241028T155359, start_date=20241028T161250, end_date=20241028T161251
[2024-10-28T16:12:51.172+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 51 for task fetch_insider_transaction_data ('data'; 1744)
[2024-10-28T16:12:51.226+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-28T16:12:51.251+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-28T16:12:51.255+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
