[2024-10-30T15:14:23.989+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-30T15:14:24.011+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Predice-Stock-ML-Pipeline.run_ml_workload manual__2024-10-30T14:27:23.134497+00:00 [queued]>
[2024-10-30T15:14:24.015+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Predice-Stock-ML-Pipeline.run_ml_workload manual__2024-10-30T14:27:23.134497+00:00 [queued]>
[2024-10-30T15:14:24.016+0000] {taskinstance.py:2306} INFO - Starting attempt 7 of 7
[2024-10-30T15:14:24.022+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_ml_workload> on 2024-10-30 14:27:23.134497+00:00
[2024-10-30T15:14:24.031+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4696) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-30T15:14:24.033+0000] {standard_task_runner.py:63} INFO - Started process 4701 to run task
[2024-10-30T15:14:24.032+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Predice-Stock-ML-Pipeline', 'run_ml_workload', 'manual__2024-10-30T14:27:23.134497+00:00', '--job-id', '328', '--raw', '--subdir', 'DAGS_FOLDER/stock_and_sentiment_ml_pipeline.py', '--cfg-path', '/tmp/tmpt5dks69k']
[2024-10-30T15:14:24.035+0000] {standard_task_runner.py:91} INFO - Job 328: Subtask run_ml_workload
[2024-10-30T15:14:24.053+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-30T15:14:24.092+0000] {task_command.py:426} INFO - Running <TaskInstance: Predice-Stock-ML-Pipeline.run_ml_workload manual__2024-10-30T14:27:23.134497+00:00 [running]> on host cf1c99cdc1a8
[2024-10-30T15:14:24.435+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Predice-Stock-ML-Pipeline' AIRFLOW_CTX_TASK_ID='run_ml_workload' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T14:27:23.134497+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-30T14:27:23.134497+00:00'
[2024-10-30T15:14:24.436+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-30T15:14:35.847+0000] {logging_mixin.py:188} INFO - Mean Squared Error for Random Forest Regression: 3.4913262575604404e-06
[2024-10-30T15:14:35.849+0000] {logging_mixin.py:188} INFO - Mean Squared Error for HistGradientBoostingRegressor: 9.76420857129024e-06
[2024-10-30T15:14:35.850+0000] {python.py:237} INFO - Done. Returned value was: (RandomForestRegressor(random_state=42), HistGradientBoostingRegressor(random_state=42))
[2024-10-30T15:14:35.853+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-30T15:14:35.881+0000] {xcom.py:675} ERROR - Object of type tuple is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2024-10-30T15:14:35.888+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 150, in serialize
    return encode(classname or serialized_classname, version, serialize(data, depth + 1))
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 127, in serialize
    return [serialize(d, depth + 1) for d in o]
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 189, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'sklearn.ensemble._forest.RandomForestRegressor'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 486, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3197, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 246, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 673, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 102, in encode
    o = self.default(o)
        ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type tuple is not JSON serializable
[2024-10-30T15:14:35.907+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Predice-Stock-ML-Pipeline, task_id=run_ml_workload, run_id=manual__2024-10-30T14:27:23.134497+00:00, execution_date=20241030T142723, start_date=20241030T151424, end_date=20241030T151435
[2024-10-30T15:14:35.921+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 328 for task run_ml_workload (Object of type tuple is not JSON serializable; 4701)
[2024-10-30T15:14:36.070+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-30T15:14:36.112+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-30T15:14:36.116+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
