[2024-10-30T14:36:06.186+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-30T14:36:06.223+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Predice-Stock-ML-Pipeline.combine_data_for_ml manual__2024-10-30T14:27:23.134497+00:00 [queued]>
[2024-10-30T14:36:06.231+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Predice-Stock-ML-Pipeline.combine_data_for_ml manual__2024-10-30T14:27:23.134497+00:00 [queued]>
[2024-10-30T14:36:06.232+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-10-30T14:36:06.242+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): combine_data_for_ml> on 2024-10-30 14:27:23.134497+00:00
[2024-10-30T14:36:06.256+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1126) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-30T14:36:06.258+0000] {standard_task_runner.py:63} INFO - Started process 1131 to run task
[2024-10-30T14:36:06.258+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Predice-Stock-ML-Pipeline', 'combine_data_for_ml', 'manual__2024-10-30T14:27:23.134497+00:00', '--job-id', '301', '--raw', '--subdir', 'DAGS_FOLDER/stock_and_sentiment_ml_pipeline.py', '--cfg-path', '/tmp/tmp351nw1_r']
[2024-10-30T14:36:06.261+0000] {standard_task_runner.py:91} INFO - Job 301: Subtask combine_data_for_ml
[2024-10-30T14:36:06.283+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-30T14:36:06.333+0000] {task_command.py:426} INFO - Running <TaskInstance: Predice-Stock-ML-Pipeline.combine_data_for_ml manual__2024-10-30T14:27:23.134497+00:00 [running]> on host cf1c99cdc1a8
[2024-10-30T14:36:06.626+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Predice-Stock-ML-Pipeline' AIRFLOW_CTX_TASK_ID='combine_data_for_ml' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T14:27:23.134497+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-30T14:27:23.134497+00:00'
[2024-10-30T14:36:06.628+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-30T14:36:06.803+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-30T14:36:06.805+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/ml_pipeline_helper.py", line 61, in combine_data_for_ml
    merged_data = preprocess_data(stock_data, news_sentiment_data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/ml_pipeline_helper.py", line 19, in preprocess_data
    news_data = news_data.drop(columns=['title', 'url', 'time_published', 'authors', 'summary', 'banner_image', 'source', 'source_domain', 'main_topic', 'cleaned_summary'])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 5344, in drop
    return super().drop(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 4711, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 4753, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 7000, in drop
    raise KeyError(f"{labels[mask].tolist()} not found in axis")
KeyError: "['banner_image', 'source', 'source_domain', 'main_topic'] not found in axis"
[2024-10-30T14:36:06.833+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Predice-Stock-ML-Pipeline, task_id=combine_data_for_ml, run_id=manual__2024-10-30T14:27:23.134497+00:00, execution_date=20241030T142723, start_date=20241030T143606, end_date=20241030T143606
[2024-10-30T14:36:06.844+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 301 for task combine_data_for_ml ("['banner_image', 'source', 'source_domain', 'main_topic'] not found in axis"; 1131)
[2024-10-30T14:36:06.893+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-30T14:36:06.919+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-30T14:36:06.923+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
